### ISSUE TITLE
Turbine Exception in 5.x versions

### ISSUE THREAD

**Issue by tferi** [bazelbuild/rules_jvm_external#1013] opened 2023-12-17 21:50 UTC
```
/external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/BUILD:1:13: Compiling Java headers external/rules_jvm_external/private/tools/java/com/github/bazelbuild/rules_jvm_external/librules_jvm_external-hjar.jar (4 source files) [for tool] failed: (Exit 1): turbine_direct_graal failed: error executing command (from target @rules_jvm_external//private/tools/java/com/github/bazelbuild/rules_jvm_external:rules_jvm_external) external/remote_java_tools_darwin_arm64/java_tools/turbine_direct_graal --output ... (remaining 32 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
java.lang.NullPointerException: attempted to use --release, but JAVA_HOME is not set
        at java.base@20.0.2/java.util.Objects.requireNonNull(Objects.java:259)
        at com.google.turbine.binder.CtSymClassBinder.bind(CtSymClassBinder.java:55)
        at com.google.turbine.main.Main.bootclasspath(Main.java:309)
        at com.google.turbine.main.Main.compile(Main.java:142)
        at com.google.turbine.main.Main.compile(Main.java:133)
        at com.google.turbine.main.Main.main(Main.java:89)
```

This is present on all current 5.x versions (tested up to 5.3) on Bazel 6.4.0, Mac OS 13.5 (Darwin Kernel Version 22.6.0), remotejdk 17.

The error consistently *does not occur* on 4.5.

The error is misleading, as it is actually the `java.home` system property that's checked in the code, *not* the `$JAVA_HOME` environment variable, so it cannot be worked around with the `(host_)?action_env` flags.

**Comment by lperron** [comment] 2023-12-29 09:56
Same for me.

**Comment by cristifalcas** [comment] 2023-12-31 02:24
same here

**Comment by ar3s3ru** [comment] 2024-01-04 17:35
I'm only getting this issue when updating `rules_java` from `7.1.0` to `7.3.1`.
With `rules_java=7.1.0` I'm able to run `rules_jvm_external=5.3`. 

On Bazel 6.4.0, using Bzlmod.

**Comment by shs96c** [comment] 2024-01-04 18:20
How do I replicate this issue? Within the repo, I've updated `example/bzlmod/MODULE.bazel` to use `rules_java` version 7.3.1, and I'm not seeing the problem.

**Comment by lperron** [comment] 2024-01-05 16:31
For or-tools, just check out the main branch, and run bazel -c opt test ortools/...
It fails on my mac M1. I have bazel 6.4.0 homebrew.

**Comment by SanjayVas** [comment] 2024-01-09 22:48
I believe the issue is specifically with rules_java > 7.2.0 with Bazel < 7. See https://github.com/bazelbuild/rules_java/issues/159

**Comment by lperron** [comment] 2024-01-10 06:59
indeed, bazel7 works fine on a legacy WORKSPACE without bzlmod.

**Comment by shs96c** [comment] 2024-01-15 16:28
It appears this is an issue with Turbine, which is part of Bazel itself. In addition, the problem only occurs when using `rules_java` with a version of bazel it's not designed to be used with. Because of both of these things, I am closing this issue.

**Closed by shs96c** 2024-01-15 16:28 UTC
